# I had to remove the name tag because it given me an error.
service: tm-code-challenge

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: todosTable
            sources: [seed-data/todos.json]

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

# Add functions
functions:
  get_todos:
    handler: handler.todos
    events:
      - http:
          method: GET
          path: todos
  post_todo:
    handler: handler.add
    events:
      - http:
          method: POST
          path: todos
  put_todo:
    handler: handler.update
    events:
      - http:
          method: PUT
          path: todos
  delete_todo:
    handler: handler.remove
    events:
      - http:
          method: DELETE
          path: todos

resources:
  Resources:
    todosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todosTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
